In [2]:
5

5

In [3]:
import numpy as np
z = np.array([[1,2],[3,4]])
print(z)

[[1 2]
 [3 4]]


In [4]:
z[0]

array([1, 2])

In [5]:
z[0][0]

1

In [6]:
print(type(z))

<class 'numpy.ndarray'>


In [7]:
np.sum(z)

10

In [8]:
print(np.max(z))
print(np.min(z))
print(np.mean(z))
print(np.std(z))

4
1
2.5
1.118033988749895


In [9]:
# Information about a matrix :
print(np.info(z))

class:  ndarray
shape:  (2, 2)
strides:  (8, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x21c4a0d43d0
byteorder:  little
byteswap:  False
type: int32
None


In [10]:
# Shape
print(np.shape(z))

(2, 2)


In [11]:
# Dimension of the matrix
print(np.ndim(z))

2


In [12]:
# Data type of elements
print(z.dtype.name)

int32


In [13]:
# Length of the ndarray
print(len(z))

2


### Menghitung waktu yang dibutuhkan cahaya matahari untuk mencapai bumi setiap hari

Ada beberapa point acuan pada formula pada task kali ini.<br>

- Time = (Distance/Speed)
- r = (a(1-e**2)/1-e cos theta)

Dalam persamaan sebelumnya, nilai suatu adalah 149.600.000 km, yang merupakan jarak sumbu semi-major, e adalah 0,0167, yang merupakan eksentrisitas orbit bumi, dan θ adalah sudut dari perihelion.

Dependent variable yang dibutuhkan adalah sebagai berikut<br>

theta = (2*phi*n) / 365.256

In [14]:
import math
import numpy as np

# Two constant using capitalization
def earth_sun_distance():
    A = 1496e5
    E = 0.0167
    l = []

    # Calculate theta as it is different of each day of year. Let's calculate the distance of the earth from the sun
    for i in range(365):
        theta = (2*math.pi*i) / 365.25
        r = A*(1-E**2) / (1-(E*math.cos(theta)))
        l.append(r)
    return l

In [15]:
# Assume the constant speed is 299.792 kms^-1
l = earth_sun_distance()
S = 299792
t = np.divide(l,S) # All value of L will divided by S

In [16]:
print(type(t))

<class 'numpy.ndarray'>


In [17]:
sunny = np.asarray(list(zip(l,t)))
print(sunny)

[[1.52098320e+08 5.07346160e+02]
 [1.52097938e+08 5.07344885e+02]
 [1.52096791e+08 5.07341061e+02]
 [1.52094881e+08 5.07334688e+02]
 [1.52092207e+08 5.07325770e+02]
 [1.52088771e+08 5.07314309e+02]
 [1.52084574e+08 5.07300308e+02]
 [1.52079617e+08 5.07283772e+02]
 [1.52073901e+08 5.07264707e+02]
 [1.52067429e+08 5.07243118e+02]
 [1.52060203e+08 5.07219014e+02]
 [1.52052224e+08 5.07192401e+02]
 [1.52043496e+08 5.07163288e+02]
 [1.52034022e+08 5.07131685e+02]
 [1.52023804e+08 5.07097602e+02]
 [1.52012847e+08 5.07061051e+02]
 [1.52001152e+08 5.07022042e+02]
 [1.51988725e+08 5.06980589e+02]
 [1.51975569e+08 5.06936705e+02]
 [1.51961688e+08 5.06890405e+02]
 [1.51947088e+08 5.06841703e+02]
 [1.51931772e+08 5.06790616e+02]
 [1.51915746e+08 5.06737159e+02]
 [1.51899015e+08 5.06681350e+02]
 [1.51881585e+08 5.06623208e+02]
 [1.51863460e+08 5.06562750e+02]
 [1.51844647e+08 5.06499997e+02]
 [1.51825152e+08 5.06434969e+02]
 [1.51804982e+08 5.06367687e+02]
 [1.51784142e+08 5.06298172e+02]
 [1.517626

We now have in systematic tabular format the values of distance between the Earth and the Sun and the time taken for light to reach the Earth. We can go on adding other parameters to our matrix, and that is the flexibility that comes with using matrices and NumPy arrays.<br>
Please note here that these values are by no means accurate, and we have made a few safe assumptions for simplicity, but it is nevertheless a good illustration of how matrices can be utilized for practically anything. Also, note that the values reflected here are in scientific notation format used in Python and can easily be converted to float or any other type as required. The values on the left are in km, and the ones on the right are in the form 507.346... seconds.


In [18]:
d = []
for i in range(1,len(l) - 1):
    d.append(l[i]-l[i-1])
print(d)

[-382.2014582455158, -1146.4797523021698, -1910.3842301666737, -2673.6658524870872, -3436.075836390257, -4197.365758448839, -4957.287656396627, -5715.5941315591335, -6472.038449823856, -7226.374643236399, -7978.357610076666, -8727.743215203285, -9474.288389235735, -10217.751227021217, -10957.891085714102, -11694.468681573868, -12427.246186107397, -13155.987321197987, -13880.457453042269, -14600.42368543148, -15315.654951184988, -16025.922103106976, -16730.998003304005, -17430.65761104226, -18124.67806968093, -18812.83879184723, -19494.921543240547, -20170.710524857044, -20839.992453813553, -21502.55664244294, -22158.19507575035, -22806.70248708129, -23447.87643235922, -24081.51736226678, -24707.428692489862, -25325.41687297821, -25935.29145383835, -26536.8651509583, -27129.953908473253, -27714.37696006894, -28289.956887602806, -28856.519678503275, -29413.894780486822, -29961.915154725313, -30500.417326390743, -31029.241434007883, -31548.23127564788, -32057.234354108572, -32556.10191896

In [19]:
z

array([[1, 2],
       [3, 4]])

In [20]:
# Transpose method 1
print(np.transpose(z))

# Transpose method 2
print(z.transpose())

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [21]:
# Flatten the array 

y = z.ravel()
print(y)

[1 2 3 4]


In [22]:
print(z == 3)

[[False False]
 [ True False]]


In [23]:
print(z < 3)

[[ True  True]
 [False False]]


In [24]:
print(z > 3)

[[False False]
 [False  True]]


In [25]:
# Reshaping matrix
r = z.reshape(4,1)
print(r)

[[1]
 [2]
 [3]
 [4]]


In [26]:
resize = np.resize(z,(3,3))
print(resize)

[[1 2 3]
 [4 1 2]
 [3 4 1]]


In [27]:
import numpy as np
z = np.array([[1,5,9,4],[8,3,7,6]])
print(z)

print(z.max(axis=0))
print(z.max(axis=1))

[[1 5 9 4]
 [8 3 7 6]]
[8 5 9 6]
[9 8]


In [28]:
print(z.sum(axis=1))

[19 24]


In [29]:
print(np.concatenate((z[1],z[0]),axis=0))

[8 3 7 6 1 5 9 4]


### Matrix Search

Tugas kali ini kita akan mencari nilai input yang diberikan dalam matrix yang diurutkan dalam urutan naik, baik barisnya maupun kolomnya. Ini akan membantu kita memahami aturan umum traversal dalam matrix, terutama jika tidak menggunakan array NumPy. Tujuan akhirnya adalah mengembalikan nilai True atau False, tergantung pada apa nilai yang ada di dalam matriks tersebut

- Define first the matrix

In [30]:
# Define first the matrix
matrix = [[7, 10, 15, 18],\
          [25, 29, 35, 47],\
           [56, 78, 85, 104]]

- Write a function, that will take this matrix as an input along with the value we have to search. We will first be covering the edge cases, which, in this instance, means where a matrix is empty or the target value is non-zero

In [31]:
def matrixsearch(matrix, value):
    if value is None or not matrix:
        return False
    row = len(matrix)
    col = len(matrix[0])
    start = 0
    end = row*col -1
    while start <= end:
        mid = int((start+end)/2)
        pointer = matrix[int(mid/col)][int(mid%col)]
        print("Pointer :",pointer)
        print(int(mid/col),int(mid%col))
        if pointer == value:
            return True
        elif pointer < value:
            start = mid + 1
        else :
            end = mid-1
    return False


sol = matrixsearch(matrix,78)
print(sol)

Pointer : 29
1 1
Pointer : 56
2 0
Pointer : 85
2 2
Pointer : 78
2 1
True


#### Multiple Matrices

In [32]:
import numpy as np
z = np.array([[1, 2],\
              [3, 4]])
x = np.array([[4, 5],\
              [7, 8]])

print(np.multiply(x,z))
print(np.multiply(z,x))

[[ 4 10]
 [21 32]]
[[ 4 10]
 [21 32]]


In [33]:
import numpy as np
z = np.array([[1, 2],\
              [3, 4]])
x = np.array([[4, 5, 6],\
              [7, 8, 9]])
print("Multiplying with a number: ")
print(np.multiply(3,x))
print(np.multiply(x,3))


Multiplying with a number: 
[[12 15 18]
 [21 24 27]]
[[12 15 18]
 [21 24 27]]


In [34]:
"""
print("Multiplication between matrices of different sizes: ")
print(np.multiply(x,z))
print(np.multiply(z,x))
"""

print("What we get here is ValueError, due to the property of arrays in NumPy known as broadcasting.")

What we get here is ValueError, due to the property of arrays in NumPy known as broadcasting.


In [35]:
import numpy as np
z = np.array([[1,2],\
              [3]])
x = np.array([[4,5]])
print(np.multiply(x,z))


[[list([1, 2, 1, 2, 1, 2, 1, 2]) list([3, 3, 3, 3, 3])]]


In [36]:
import numpy as np
from numpy.linalg import inv

def identity():
    print(np.identity(3))

def eye():
    print(np.eye(3,k=1))

def inverse():
    z = np.array([[1,2],[3,4]])
    z_inv = inv(z)
    product = np.dot(z, z_inv)
    print(z_inv)
    print(product)

In [37]:
identity()
eye()
inverse()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [38]:
# Logical Operator

def and_op_1():
    m1 = [True, False, False]
    m2 = [True, False, True]
    print(np.logical_and(m1, m2))

def and_op_2():
    m1 = [0, 1, 0]
    m2 = [1, 1, 0]
    print(np.logical_and(m1, m2))

and_op_1()
and_op_2()

[ True False False]
[False  True False]


In [39]:
# Outer Function or Vector Product

def vector():
    horizontal = np.array([[1,3,2]])
    vertical = np.array([[2],\
                         [0],\
                         [1]])
    print("Output for dimension 1 x 1: ")
    print(horizontal.dot(vertical))
    print("Output for dimension 3 x 3: ")
    print(vertical.dot(horizontal))
    print("Output using outer for getting cross product: ")
    print(np.outer(vertical.ravel(), horizontal.ravel()))
    print(np.outer(horizontal.ravel(), vertical.ravel()))

vector()

Output for dimension 1 x 1: 
[[4]]
Output for dimension 3 x 3: 
[[2 6 4]
 [0 0 0]
 [1 3 2]]
Output using outer for getting cross product: 
[[2 6 4]
 [0 0 0]
 [1 3 2]]
[[2 0 1]
 [6 0 3]
 [4 0 2]]


### Use of Matrices in Performing Linear Equations

John is out of town for three days and in a mood to spend until he exhausts his resources. He has three denominations of currency with him. On the first day, John spends $435 on the latest electronic tablet that he likes, on which he spends 37 of type a denomination, 20 of type b, and 12 of type c. On the second day, he goes skydiving and spends 15, 32, and 4 of denominations a, b, and c, respectively, a total of $178. On the third day, with whatever amount he is left with, he decides to go to the theatre, which costs $70, and he shells out 5, 40, and 2 of the a, b, and c denominations, respectively. Can you tell what the values of the respective denominations are?

- Pertama, define variable 3  hari dalam matrix menggunakan array numpy

In [40]:
# Ax = B

import numpy as np
z = np.array([[37,20,12],[15,32,4],[5,40,2]])
r = np.array([[435],[178],[70]])

# First calculate the inverse of matrix A
print(np.linalg.inv(z))

# Use the dot product an assign it into variable X
X = np.linalg.inv(z).dot(r)
print(X) # Solved

# This same thing can be done even more easily with the help of another NumPy function called solve(). Let's name the output variable here as y.
y = np.linalg.solve(z,r)
print(y) # Solved

[[-0.06282723  0.28795812 -0.19895288]
 [-0.0065445   0.0091623   0.02094241]
 [ 0.28795812 -0.90314136  0.57853403]]
[[10.  ]
 [ 0.25]
 [ 5.  ]]
[[10.  ]
 [ 0.25]
 [ 5.  ]]


Thus, we can see that the output after using both methods 1 and 2 is the same, which is $10, 25 cents, and $5, which are the respective denominations that we were trying to establish.

### Menemukan Probabilitas dari State Transitions

Anda diberikan sebuah array berisi 4 keadaan, yakni [A,B,C,D], di mana array ini dihasilkan secara acak. Selanjutnya, kita harus mencari probabilitas transisi 4 keadaan ini, di mana setelah ini, kita akan membentuk matrix transisi darinya. Mari implementasikan Markov Chains

- Gunakan library <i>random</i>. Setelah itu, tentukan berapa banyak elemen yang ingin kita jadikan sebagai konstanta, LEN_STR, yang mana dalam hal ini, akan kita atur menjadi 50

In [41]:
import random

tokens = []
LEN_STR = 50
for i in range(LEN_STR):
    tokens.append(random.choice("ABCD"))

print(tokens)

['C', 'B', 'D', 'A', 'B', 'A', 'A', 'A', 'A', 'C', 'D', 'A', 'D', 'A', 'D', 'B', 'C', 'D', 'C', 'C', 'A', 'D', 'B', 'A', 'C', 'B', 'D', 'C', 'D', 'B', 'B', 'C', 'D', 'C', 'D', 'A', 'C', 'D', 'A', 'A', 'B', 'C', 'A', 'C', 'D', 'D', 'B', 'D', 'D', 'A']


- Temukan relative value, dan konversi mereka menjadi integer, di mana integer ini sendiri sangat mudah untuk kalkulasi secara cepat

In [42]:
relative_value = [(ord(t) - ord('A')) for t in tokens]
print(relative_value)

[2, 1, 3, 0, 1, 0, 0, 0, 0, 2, 3, 0, 3, 0, 3, 1, 2, 3, 2, 2, 0, 3, 1, 0, 2, 1, 3, 2, 3, 1, 1, 2, 3, 2, 3, 0, 2, 3, 0, 0, 1, 2, 0, 2, 3, 3, 1, 3, 3, 0]


- Sekarang, temukan perbedaan  antara ilai ASCII dan masukkan ke dalam sebuah list.

In [44]:
LEN_TOKENS = len("ABCD")
m = [[0]*LEN_TOKENS for j in range(LEN_TOKENS)]
print(m)

for (i,j) in zip(relative_value, relative_value[1:]):
    m[i][j] += 1

print(list(zip(relative_value, relative_value[1:])))
print(m)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[(2, 1), (1, 3), (3, 0), (0, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 2), (2, 3), (3, 0), (0, 3), (3, 0), (0, 3), (3, 1), (1, 2), (2, 3), (3, 2), (2, 2), (2, 0), (0, 3), (3, 1), (1, 0), (0, 2), (2, 1), (1, 3), (3, 2), (2, 3), (3, 1), (1, 1), (1, 2), (2, 3), (3, 2), (2, 3), (3, 0), (0, 2), (2, 3), (3, 0), (0, 0), (0, 1), (1, 2), (2, 0), (0, 2), (2, 3), (3, 3), (3, 1), (1, 3), (3, 3), (3, 0)]
[[4, 2, 4, 3], [2, 1, 3, 3], [2, 2, 1, 7], [6, 4, 3, 2]]


Di sini, kita sudah menginisiasi matrix nol berdasarkan ukuran LEN_TOKENS, yang kita define secara konstan untuk membangun matrix nol.

- Selanjutnya, kita akan membuat probabilitas, yang mana ini merupakan frekuensi relatif terhadap baris tertentu. Sebagai contoh, transisi dari A ke A adalah 8, dan total transisi dari A ke keadaan apapun adalah 20. Jadi, peluangnya adalah (8/20) = 0.4

In [45]:
for state in m:
    total = sum(state)
    if total>0:
        state[:] = [float(f)/sum(state) for f in state]

- Cetak hasil statenya

In [46]:
for state in m:
    print(state)

[0.3076923076923077, 0.15384615384615385, 0.3076923076923077, 0.23076923076923078]
[0.2222222222222222, 0.1111111111111111, 0.3333333333333333, 0.3333333333333333]
[0.16666666666666666, 0.16666666666666666, 0.08333333333333333, 0.5833333333333334]
[0.4, 0.26666666666666666, 0.2, 0.13333333333333333]


Dengan demikian, kita dapat membangun matriks transisi untuk menggambarkan transisi keadaan, yang menunjukkan kepada kita probabilitas transisi dari satu keadaan ke keadaan berikutnya. Jadi, kemungkinan A menemukan A sebagai huruf berikutnya adalah 0,4 , A menuju B adalah 0,15 , dan seterusnya

### Building a Text Predictor Using Markov Chain

Tujuannya adalah membangun prediktor teks kita sendiri. Pertama kita harus membuat list yang menjelaskan transisi status dengan membuat korelasi antar kata yang diberikan dan kata yang mengikutinya. Setelah itu, kita lakukan sorting pada list yang telah dibuyat, dan buat hash table dengan mengelompokkan kata yang mengikuti kata-kata tertentu pada posisi yang berbeda. Setelah itu gunakan random word generator untuk membuat dan mengarahkan value nya pada kata pertama.

Ada beberapa cara untuk menyelesaikan masalah ini, dan cara yang paling mudahlah yang akan kita ambil. Sebenarnya, memprediksi teks lebih sulit dari yang biasanya.

- Pertama, list kata kata di simpan dalam text file. Setelah itu, kita import dalam source code kita

In [54]:
churchill = open('churchill.txt', encoding='utf-8').read()
keywords = churchill.split()
print(keywords)

['The', 'position', 'of', 'the', 'B.', 'E.F', 'had', 'now', 'become', 'critical', 'As', 'a', 'result', 'of', 'a', 'most', 'skillfully', 'conducted', 'retreat', 'and', 'German', 'errors,', 'the', 'bulk', 'of', 'the', 'British', 'Forces', 'reached', 'the', 'Dunkirk', 'bridgehead.', 'The', 'peril', 'facing', 'the', 'British', 'nation', 'was', 'now', 'suddenly', 'and', 'universally', 'perceived.', 'On', 'May', '26,', '“Operation', 'Dynamo', '“–the', 'evacuation', 'from', 'Dunkirk', 'began.', 'The', 'seas', 'remained', 'absolutely', 'calm.', 'The', 'Royal', 'Air', 'Force–bitterly', 'maligned', 'at', 'the', 'time', 'by', 'the', 'Army–fought', 'vehemently', 'to', 'deny', 'the', 'enemy', 'the', 'total', 'air', 'supremacy', 'which', 'would', 'have', 'wrecked', 'the', 'operation.', 'At', 'the', 'outset,', 'it', 'was', 'hoped', 'that', '45,000', 'men', 'might', 'be', 'evacuated;', 'in', 'the', 'event,', 'over', '338,000', 'Allied', 'troops', 'reached', 'England,', 'including', '26,000', 'French',

- Iterasi list nya, dan tambahkan elements-element ini ke list yang baru, yang akan menyimpan keyword dan kata yang akan mengikutinya

In [55]:
keylist = []
for i in range(len(keywords)-1):
    keylist.append((keywords[i], keywords[i+1]))
print(keylist)

[('The', 'position'), ('position', 'of'), ('of', 'the'), ('the', 'B.'), ('B.', 'E.F'), ('E.F', 'had'), ('had', 'now'), ('now', 'become'), ('become', 'critical'), ('critical', 'As'), ('As', 'a'), ('a', 'result'), ('result', 'of'), ('of', 'a'), ('a', 'most'), ('most', 'skillfully'), ('skillfully', 'conducted'), ('conducted', 'retreat'), ('retreat', 'and'), ('and', 'German'), ('German', 'errors,'), ('errors,', 'the'), ('the', 'bulk'), ('bulk', 'of'), ('of', 'the'), ('the', 'British'), ('British', 'Forces'), ('Forces', 'reached'), ('reached', 'the'), ('the', 'Dunkirk'), ('Dunkirk', 'bridgehead.'), ('bridgehead.', 'The'), ('The', 'peril'), ('peril', 'facing'), ('facing', 'the'), ('the', 'British'), ('British', 'nation'), ('nation', 'was'), ('was', 'now'), ('now', 'suddenly'), ('suddenly', 'and'), ('and', 'universally'), ('universally', 'perceived.'), ('perceived.', 'On'), ('On', 'May'), ('May', '26,'), ('26,', '“Operation'), ('“Operation', 'Dynamo'), ('Dynamo', '“–the'), ('“–the', 'evacuati

- Selanjutnya, kita inisiasi sebuah dictionary word_dict. Setelah itu, kita iterasi lagi keylist yang sudah ada, dan menambahkan kata-katanya.

In [57]:
word_dict = {}

for beginning, following in keylist:
    if beginning in word_dict.keys():
        word_dict[beginning].append(following)
    else:
        word_dict[beginning] = [following]

print(word_dict)

{'The': ['position', 'peril', 'seas', 'Royal', 'French', 'Guards', 'Rifle', 'British', 'Belgian,', 'whole', 'King', 'surrender', 'enemy', 'numbers', 'hospital', 'enemy', 'Royal', 'great', 'Knights', 'President', 'best', 'French', 'whole', 'British'], 'position': ['of'], 'of': ['the', 'a', 'the', 'Commons,', 'national', 'the', 'May,', 'the', 'the', 'this', 'the', 'over', 'the', 'Belgium.', 'the', 'General', 'the', 'the', 'the', 'about', 'different', 'German', 'the', 'liberties', 'desperate', 'British', 'intense', 'a', 'their', 'the', 'Dunkirk', 'the', 'retreat', 'the', 'the', 'the', 'food', 'the', 'the', 'the', 'retreat', 'his', 'retreat.', 'the', 'the', 'Allied', 'their', 'hostile', 'which', 'the', 'them-together', 'infantry', 'countless', 'bombs', 'artillery', 'their', 'British', 'its', 'deliverance,', 'the', 'at', 'all', 'the', 'death', 'a', 'our', 'this;', 'my', 'strength', 'thousands?', 'greater', 'the', 'German', 'one-quarter', 'their', 'the', 'a', 'our', 'a', 'armored', 'civiliza

- Next, kita buat predictor kita sendiri. Pertama, define NumPy string, yang akan mengambil string secara acak sebagai pilihan dari kumpulan keywords sebelumnya

In [58]:
first_word = np.random.choice(keywords)

while first_word.islower():
    first_word = np.random.choice(keywords)

In [60]:
word_chain = [first_word]

In [70]:
WORDCOUNT = 0
for i in range(WORDCOUNT):
    word_chain.append(np.random.choice(word_dict[word_chain[-1]]))


- Terakhir, define variable string <i>sentence</i>

In [71]:
sentence = ' '.join(word_chain)
print(sentence)

I will last, depends upon which brought forth a large number of civilization itself will be our only against serious loss certainly the Queen Victoria’s Rifles, and French Army of all the enemy was hurled back into the time more powerful military strength. Even though large formations of countless merchant seamen, strained every kind would have proved to surrender. He and the Crusaders, all the north were still anxious. The whole of Europe and artillery, hurled themselves in the fact that follow from this country, but not feel not be my hard and fierce. Suddenly the trampling down in all sides with growing strength to his hands, with a week ago. The great strength of the time and the enemy. But it will not also against the Armies were frustrated in this further delay on so many reported missing who will see, contact
