In [3]:
14

14

In [4]:
import random
import math

import numpy as np
import pandas as pd

from timeit import Timer

In [5]:
my_list = list(range(10**6))
my_array = np.array(my_list)

In [6]:
def for_add():
    return [item + 1 for item in my_list]

def vec_add():
    return my_array + 1

In [7]:
print("For loop addition :")
print(min(Timer(for_add).repeat(10, 10)))
print("Vectorized addition :")
print(min(Timer(vec_add).repeat(10,10)))

For loop addition :
0.9071102999999994
Vectorized addition :
0.02028190000000052


In [8]:
def for_mul():
    return [item * 2 for item in my_list]

def vec_mul():
    return my_array * 2

print('For-loop multiplication:')
print(min(Timer(for_mul).repeat(10, 10)))
print('Vectorized multiplication:')
print(min(Timer(vec_mul).repeat(10, 10)))

For-loop multiplication:
0.8901693999999978
Vectorized multiplication:
0.02260939999999323


In [9]:
import math

def for_sqrt():
    return [math.sqrt(item) for item in my_list]

def vec_sqrt():
    return np.sqrt(my_array)

print('For-loop square root:')
print(min(Timer(for_sqrt).repeat(10, 10)))
print('Vectorized square root:')
print(min(Timer(vec_sqrt).repeat(10, 10)))

For-loop square root:
1.9920068000000057
Vectorized square root:
0.09062090000000467


In [10]:
sample = np.random.normal()
sample

-0.2612398266621311

In [11]:
sample = np.random.normal(loc=100, scale=10)
sample

105.0556219718325

In [12]:
sample = np.random.normal(loc=100, scale=10,size=(2,3))
sample

array([[103.19967645, 105.9063432 , 103.7732776 ],
       [101.83288739, 115.66511123,  99.15803014]])

In [13]:
samples = np.random.poisson(lam=10, size=(2,2))
samples

array([[12, 11],
       [21,  9]])

In [14]:
np.random.randint(low=0, high=5, size=(2,5))

array([[2, 2, 2, 1, 0],
       [1, 4, 0, 3, 4]])

In [15]:
np.random.choice([1,3,4,-6], size=(2, 2))

array([[ 3, -6],
       [ 1,  4]])

In [16]:
a = [1,2,3,4]
for _ in range(3):
    np.random.shuffle(a)
    print(a)

[2, 1, 3, 4]
[2, 1, 4, 3]
[4, 1, 2, 3]


In [17]:
import random

random.seed(0)

In [18]:
import pandas as pd

my_dict = {'col1': [1, 2], 'col2': np.array([3, 4]),'col3': [5, 6]}
df = pd.DataFrame(my_dict)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [19]:
my_array = np.array([[1, 3, 5], [2, 4, 6]])
alt_df = pd.DataFrame(my_array, columns=['col1', 'col2', 'col3'])
alt_df

col1  col2  col3
0     1     3     5
1     2     4     6

In [21]:
df.loc[1]

col1    2
col2    4
col3    6
Name: 1, dtype: int64

In [22]:
df.loc[0]

col1    1
col2    3
col3    5
Name: 0, dtype: int64

In [25]:
df.loc[[1,0]]

col1  col2  col3
1     2     4     6
0     1     3     5

In [26]:
df.loc[[0,1]]

col1  col2  col3
0     1     3     5
1     2     4     6

In [27]:
df.loc[0, ['col2', 'col3']]

col2    3
col3    5
Name: 0, dtype: int64

In [28]:
for item in df.loc[:,'col3']:
    print(item)

5
6


In [29]:
df.loc[0] = [3,6,9]
df

col1  col2  col3
0     3     6     9
1     2     4     6

In [30]:
df['col2'] = [0,0]
df

col1  col2  col3
0     3     0     9
1     2     0     6

In [31]:
df['col4'] = [10,10]
df

col1  col2  col3  col4
0     3     0     9    10
1     2     0     6    10

In [32]:
df.loc[3] = [1,2,3,4]

In [33]:
df

col1  col2  col3  col4
0     3     0     9    10
1     2     0     6    10
3     1     2     3     4

In [42]:
df = pd.read_csv('D:\RESEARCH\Dasarnya\MATH\Step_4_Statistics and Calculus Python\Source Code\The-Statistics-and-Calculus-with-Python-Workshop\Chapter02\Exercise2.02\dataset.csv',index_col='id')

In [43]:
df

x    y     z
id              
0   1  1.0   3.0
1   1  0.0   9.0
2   1  3.0   NaN
3   2  0.0  10.0
4   1  NaN   4.0
5   2  2.0   3.0

In [44]:
df = df.rename(columns = {'x':'col_x','y':'col_y','z':'col_z'})

In [45]:
df

col_x  col_y  col_z
id                     
0       1    1.0    3.0
1       1    0.0    9.0
2       1    3.0    NaN
3       2    0.0   10.0
4       1    NaN    4.0
5       2    2.0    3.0

In [46]:
df = df.fillna(0)
df

col_x  col_y  col_z
id                     
0       1    1.0    3.0
1       1    0.0    9.0
2       1    3.0    0.0
3       2    0.0   10.0
4       1    0.0    4.0
5       2    2.0    3.0

In [47]:
df = df.astype(int)
df

col_x  col_y  col_z
id                     
0       1      1      3
1       1      0      9
2       1      3      0
3       2      0     10
4       1      0      4
5       2      2      3

In [48]:
df = df.drop([1,3,4], axis=0)
df

col_x  col_y  col_z
id                     
0       1      1      3
2       1      3      0
5       2      2      3

In [49]:
zero_df = pd.DataFrame(np.zeros((2,3)),columns=['col_x','col_y','col_z'])
zero_df

col_x  col_y  col_z
0    0.0    0.0    0.0
1    0.0    0.0    0.0

In [50]:
df = pd.concat([df, zero_df], axis=0)
df

col_x  col_y  col_z
0    1.0    1.0    3.0
2    1.0    3.0    0.0
5    2.0    2.0    3.0
0    0.0    0.0    0.0
1    0.0    0.0    0.0

In [51]:
df = df.sort_values('col_x', axis=0)
df

col_x  col_y  col_z
0    0.0    0.0    0.0
1    0.0    0.0    0.0
0    1.0    1.0    3.0
2    1.0    3.0    0.0
5    2.0    2.0    3.0

In [52]:
df = df.astype(int)
df.to_csv('D:\RESEARCH\Dasarnya\MATH\Step_4_Statistics and Calculus Python\My Source Code\Work_2\output.csv', index=False)

In [53]:
df = pd.DataFrame({'x':[1,2,-1],'y':[-3,6,5],'z':[1,3,2]})
df

x  y  z
0  1 -3  1
1  2  6  3
2 -1  5  2

In [54]:
df['x_squared'] = df['x'].apply(lambda x: x**2)
df

x  y  z  x_squared
0  1 -3  1          1
1  2  6  3          4
2 -1  5  2          1

In [55]:
def parity_str(x):
    if x%2 == 0:
        return 'even'
    return 'odd'

df['x_parity'] = df['x'].apply(parity_str)
df

x  y  z  x_squared x_parity
0  1 -3  1          1      odd
1  2  6  3          4     even
2 -1  5  2          1      odd