In [2]:
import random
import math

import numpy as np
from timeit import Timer

In [3]:
my_list = list(range(10**6))
my_array = np.array(my_list)

In [6]:
def for_add():
    return [item + 1 for item in my_list]

def vec_add():
    return my_array + 1

In [8]:
print("For loop addition :")
print(min(Timer(for_add).repeat(10, 10)))
print("Vectorized addition :")
print(min(Timer(vec_add).repeat(10,10)))

For loop addition :
0.8675077000000044
Vectorized addition :
0.020213699999999335


In [9]:
def for_mul():
    return [item * 2 for item in my_list]

def vec_mul():
    return my_array * 2

print('For-loop multiplication:')
print(min(Timer(for_mul).repeat(10, 10)))
print('Vectorized multiplication:')
print(min(Timer(vec_mul).repeat(10, 10)))

For-loop multiplication:
0.9027935000000014
Vectorized multiplication:
0.022365200000024288


In [10]:
import math

def for_sqrt():
    return [math.sqrt(item) for item in my_list]

def vec_sqrt():
    return np.sqrt(my_array)

print('For-loop square root:')
print(min(Timer(for_sqrt).repeat(10, 10)))
print('Vectorized square root:')
print(min(Timer(vec_sqrt).repeat(10, 10)))

For-loop square root:
1.8752564999999777
Vectorized square root:
0.09188480000000254


In [11]:
sample = np.random.normal()
sample

-0.6125983610379656

In [13]:
sample = np.random.normal(loc=100, scale=10)
sample

93.31745755396577

In [14]:
sample = np.random.normal(loc=100, scale=10,size=(2,3))
sample

array([[ 97.32372182,  98.03957856, 107.56444445],
       [ 97.14014435, 112.56024698, 108.83998913]])

In [16]:
samples = np.random.poisson(lam=10, size=(2,2))
samples

array([[10, 14],
       [ 6, 10]])

In [20]:
np.random.randint(low=0, high=5, size=(2,5))

array([[3, 4, 1, 0, 2],
       [1, 2, 3, 3, 2]])

In [21]:
np.random.choice([1,3,4,-6], size=(2, 2))

array([[ 3, -6],
       [ 3, -6]])

In [24]:
a = [1,2,3,4]
for _ in range(3):
    np.random.shuffle(a)
    print(a)

[4, 2, 3, 1]
[4, 2, 3, 1]
[1, 4, 3, 2]


In [26]:
import random

random.seed(0)

In [27]:
import pandas as pd

my_dict = {'col1': [1, 2], 'col2': np.array([3, 4]),'col3': [5, 6]}
df = pd.DataFrame(my_dict)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [28]:
my_array = np.array([[1, 3, 5], [2, 4, 6]])
alt_df = pd.DataFrame(my_array, columns=['col1', 'col2', 'col3'])
alt_df

col1  col2  col3
0     1     3     5
1     2     4     6